import type { TableDef, DatabaseDef, ViewDef } from './types';

// ---------------------------------------------------------------------------
// Shared select option palettes
// ---------------------------------------------------------------------------

const STATUS_OPTIONS = [
  { value: 'draft', label: 'Draft', color: '#6b7280' },
  { value: 'published', label: 'Published', color: '#22c55e' },
  { value: 'archived', label: 'Archived', color: '#f59e0b' },
  { value: 'active', label: 'Active', color: '#3b82f6' },
  { value: 'inactive', label: 'Inactive', color: '#ef4444' },
  { value: 'pending', label: 'Pending', color: '#a855f7' },
  { value: 'open', label: 'Open', color: '#22c55e' },
  { value: 'closed', label: 'Closed', color: '#ef4444' },
];

const TASK_STATUS_OPTIONS = [
  { value: 'backlog', label: 'Backlog', color: '#6b7280' },
  { value: 'todo', label: 'To Do', color: '#f59e0b' },
  { value: 'in_progress', label: 'In Progress', color: '#3b82f6' },
  { value: 'in_review', label: 'In Review', color: '#8b5cf6' },
  { value: 'done', label: 'Done', color: '#22c55e' },
  { value: 'cancelled', label: 'Cancelled', color: '#ef4444' },
];

const PRIORITY_OPTIONS = [
  { value: 'none', label: 'None', color: '#6b7280' },
  { value: 'low', label: 'Low', color: '#22c55e' },
  { value: 'medium', label: 'Medium', color: '#f59e0b' },
  { value: 'high', label: 'High', color: '#f97316' },
  { value: 'urgent', label: 'Urgent', color: '#ef4444' },
  { value: 'critical', label: 'Critical', color: '#dc2626' },
];

const JOB_TYPE_OPTIONS = [
  { value: 'full-time', label: 'Full-Time', color: '#3b82f6' },
  { value: 'part-time', label: 'Part-Time', color: '#8b5cf6' },
  { value: 'contract', label: 'Contract', color: '#f59e0b' },
  { value: 'freelance', label: 'Freelance', color: '#06b6d4' },
  { value: 'internship', label: 'Internship', color: '#ec4899' },
  { value: 'volunteer', label: 'Volunteer', color: '#22c55e' },
];

const CATEGORY_OPTIONS = [
  { value: 'music', label: 'Music', color: '#ec4899' },
  { value: 'visual-arts', label: 'Visual Arts', color: '#8b5cf6' },
  { value: 'film', label: 'Film', color: '#f59e0b' },
  { value: 'dance', label: 'Dance', color: '#06b6d4' },
  { value: 'theatre', label: 'Theatre', color: '#ef4444' },
  { value: 'literature', label: 'Literature', color: '#22c55e' },
  { value: 'digital', label: 'Digital', color: '#3b82f6' },
  { value: 'community', label: 'Community', color: '#a855f7' },
  { value: 'technology', label: 'Technology', color: '#14b8a6' },
  { value: 'business', label: 'Business', color: '#f97316' },
  { value: 'health', label: 'Health', color: '#10b981' },
  { value: 'education', label: 'Education', color: '#6366f1' },
];

const CYCLE_STATUS_OPTIONS = [
  { value: 'planned', label: 'Planned', color: '#6b7280' },
  { value: 'active', label: 'Active', color: '#3b82f6' },
  { value: 'completed', label: 'Completed', color: '#22c55e' },
  { value: 'cancelled', label: 'Cancelled', color: '#ef4444' },
];

const MODULE_STATUS_OPTIONS = [
  { value: 'planned', label: 'Planned', color: '#6b7280' },
  { value: 'active', label: 'Active', color: '#3b82f6' },
  { value: 'completed', label: 'Completed', color: '#22c55e' },
  { value: 'on_hold', label: 'On Hold', color: '#f59e0b' },
  { value: 'cancelled', label: 'Cancelled', color: '#ef4444' },
];

const EPIC_STATUS_OPTIONS = [
  { value: 'not_started', label: 'Not Started', color: '#6b7280' },
  { value: 'in_progress', label: 'In Progress', color: '#3b82f6' },
  { value: 'completed', label: 'Completed', color: '#22c55e' },
  { value: 'blocked', label: 'Blocked', color: '#ef4444' },
];

const DISCUSSION_TYPE_OPTIONS = [
  { value: 'question', label: 'Question', color: '#3b82f6' },
  { value: 'discussion', label: 'Discussion', color: '#22c55e' },
  { value: 'announcement', label: 'Announcement', color: '#f59e0b' },
  { value: 'feedback', label: 'Feedback', color: '#a855f7' },
];

// ---------------------------------------------------------------------------
// Table Definitions — Complete Platform Coverage
// ---------------------------------------------------------------------------

const ALL_TABLES: TableDef[] = [
  // ==================== PLATFORM CORE ====================
  {
    id: 'jobs',
    name: 'Jobs',
    icon: '💼',
    color: '#3b82f6',
    endpoint: '/jobs',
    description: 'Job postings & opportunities',
    responseKeys: ['items', 'jobs', 'results'],
    fields: [
      { id: 'logo_url', title: 'Logo', type: 'image', width: 60, visible: true },
      { id: 'title', title: 'Title', type: 'text', width: 280, visible: true, primary: true },
      { id: 'organization', title: 'Organization', type: 'text', width: 200, visible: true },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: STATUS_OPTIONS },
      { id: 'opportunity_type', title: 'Type', type: 'singleSelect', width: 120, visible: true, options: JOB_TYPE_OPTIONS },
      { id: 'location', title: 'Location', type: 'text', width: 160, visible: true },
      { id: 'compensation', title: 'Compensation', type: 'text', width: 150, visible: true },
      { id: 'category', title: 'Category', type: 'singleSelect', width: 140, visible: true, options: CATEGORY_OPTIONS },
      { id: 'cover_image_url', title: 'Cover Image', type: 'image', width: 80, visible: false },
      { id: 'external_apply_url', title: 'Apply URL', type: 'url', width: 200, visible: false },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'requirements', title: 'Requirements', type: 'longText', width: 300, visible: false },
      { id: 'is_featured', title: 'Featured', type: 'checkbox', width: 80, visible: true },
      { id: 'view_count', title: 'Views', type: 'number', width: 80, visible: true },
      { id: 'application_count', title: 'Applications', type: 'number', width: 100, visible: false },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
      { id: 'deadline', title: 'Deadline', type: 'date', width: 130, visible: true },
    ],
  },
  {
    id: 'news',
    name: 'News',
    icon: '📰',
    color: '#a855f7',
    endpoint: '/api/news-cms/articles',
    description: 'Articles & coverage',
    responseKeys: ['items', 'articles', 'results'],
    fields: [
      { id: 'feature_image_url', title: 'Image', type: 'image', width: 60, visible: true },
      { id: 'title', title: 'Title', type: 'text', width: 300, visible: true, primary: true },
      { id: 'author_name', title: 'Author', type: 'text', width: 160, visible: true },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: STATUS_OPTIONS },
      { id: 'category', title: 'Category', type: 'text', width: 140, visible: true },
      { id: 'content_type', title: 'Type', type: 'text', width: 100, visible: true },
      { id: 'excerpt', title: 'Excerpt', type: 'longText', width: 280, visible: true },
      { id: 'image_url', title: 'Body Image', type: 'image', width: 60, visible: false },
      { id: 'video_url', title: 'Video', type: 'url', width: 200, visible: false },
      { id: 'source_url', title: 'Source', type: 'url', width: 200, visible: false },
      { id: 'published_at', title: 'Published', type: 'date', width: 130, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
      { id: 'updated_at', title: 'Updated', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'directory',
    name: 'Services',
    icon: '📍',
    color: '#06b6d4',
    endpoint: '/services',
    description: 'Community services directory',
    responseKeys: ['items', 'services', 'results'],
    fields: [
      { id: 'image_url', title: 'Image', type: 'image', width: 60, visible: true },
      { id: 'name', title: 'Name', type: 'text', width: 260, visible: true, primary: true },
      { id: 'category_names', title: 'Categories', type: 'text', width: 160, visible: true },
      { id: 'address', title: 'Address', type: 'text', width: 240, visible: true },
      { id: 'province', title: 'Province', type: 'text', width: 100, visible: true },
      { id: 'website', title: 'Website', type: 'url', width: 200, visible: true },
      { id: 'view_count', title: 'Views', type: 'number', width: 80, visible: true },
      { id: 'rating', title: 'Rating', type: 'rating', width: 100, visible: true },
      { id: 'is_verified', title: 'Verified', type: 'checkbox', width: 80, visible: true },
      { id: 'overview', title: 'Overview', type: 'longText', width: 300, visible: false },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'profiles',
    name: 'Profiles',
    icon: '👥',
    color: '#ec4899',
    endpoint: '/profiles',
    description: 'User & creative profiles',
    responseKeys: ['items', 'profiles', 'results'],
    fields: [
      { id: 'avatar_url', title: 'Avatar', type: 'image', width: 50, visible: true },
      { id: 'display_name', title: 'Name', type: 'text', width: 200, visible: true, primary: true },
      { id: 'username', title: 'Username', type: 'text', width: 150, visible: true },
      { id: 'location', title: 'Location', type: 'text', width: 160, visible: true },
      { id: 'bio', title: 'Bio', type: 'longText', width: 280, visible: true },
      { id: 'website', title: 'Website', type: 'url', width: 180, visible: true },
      { id: 'followers_count', title: 'Followers', type: 'number', width: 90, visible: true },
      { id: 'following_count', title: 'Following', type: 'number', width: 90, visible: true },
      { id: 'posts_count', title: 'Posts', type: 'number', width: 70, visible: true },
      { id: 'created_at', title: 'Joined', type: 'date', width: 130, visible: true },
    ],
  },

  // ==================== PROJECT MANAGEMENT ====================
  {
    id: 'projects',
    name: 'Projects',
    icon: '📋',
    color: '#6366f1',
    endpoint: '/api/projects',
    description: 'All projects',
    responseKeys: ['items', 'projects', 'results'],
    fields: [
      { id: 'cover_image', title: 'Cover', type: 'image', width: 60, visible: true },
      { id: 'name', title: 'Name', type: 'text', width: 260, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: true },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: STATUS_OPTIONS },
      { id: 'identifier', title: 'Key', type: 'text', width: 80, visible: true },
      { id: 'network', title: 'Network', type: 'text', width: 100, visible: true },
      { id: 'emoji', title: 'Icon', type: 'text', width: 60, visible: false },
      { id: 'member_count', title: 'Members', type: 'number', width: 80, visible: true },
      { id: 'task_count', title: 'Tasks', type: 'number', width: 80, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
      { id: 'updated_at', title: 'Updated', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'tasks',
    name: 'Tasks',
    icon: '✅',
    color: '#22c55e',
    endpoint: '/api/projects/default/tasks',
    description: 'Tasks & work items',
    responseKeys: ['items', 'tasks', 'results'],
    fields: [
      { id: 'title', title: 'Title', type: 'text', width: 300, visible: true, primary: true },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 130, visible: true, options: TASK_STATUS_OPTIONS },
      { id: 'priority', title: 'Priority', type: 'singleSelect', width: 110, visible: true, options: PRIORITY_OPTIONS },
      { id: 'assignee_name', title: 'Assignee', type: 'text', width: 150, visible: true },
      { id: 'project_name', title: 'Project', type: 'text', width: 150, visible: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'due_date', title: 'Due Date', type: 'date', width: 130, visible: true },
      { id: 'start_date', title: 'Start Date', type: 'date', width: 130, visible: false },
      { id: 'estimate', title: 'Estimate', type: 'number', width: 80, visible: false },
      { id: 'parent_task_id', title: 'Parent', type: 'text', width: 100, visible: false },
      { id: 'label_names', title: 'Labels', type: 'text', width: 160, visible: true },
      { id: 'subtask_count', title: 'Subtasks', type: 'number', width: 80, visible: false },
      { id: 'comment_count', title: 'Comments', type: 'number', width: 80, visible: false },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
      { id: 'updated_at', title: 'Updated', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'cycles',
    name: 'Cycles',
    icon: '🔄',
    color: '#14b8a6',
    endpoint: '/projects/default/cycles',
    description: 'Sprint cycles',
    responseKeys: ['items', 'cycles', 'results'],
    fields: [
      { id: 'name', title: 'Name', type: 'text', width: 240, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: CYCLE_STATUS_OPTIONS },
      { id: 'start_date', title: 'Start', type: 'date', width: 130, visible: true },
      { id: 'end_date', title: 'End', type: 'date', width: 130, visible: true },
      { id: 'total_tasks', title: 'Tasks', type: 'number', width: 80, visible: true },
      { id: 'completed_tasks', title: 'Completed', type: 'number', width: 90, visible: true },
      { id: 'progress', title: 'Progress', type: 'percent', width: 90, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'modules',
    name: 'Modules',
    icon: '📦',
    color: '#f97316',
    endpoint: '/projects/default/modules',
    description: 'Feature modules',
    responseKeys: ['items', 'modules', 'results'],
    fields: [
      { id: 'name', title: 'Name', type: 'text', width: 240, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: MODULE_STATUS_OPTIONS },
      { id: 'lead_name', title: 'Lead', type: 'text', width: 150, visible: true },
      { id: 'start_date', title: 'Start', type: 'date', width: 130, visible: true },
      { id: 'target_date', title: 'Target', type: 'date', width: 130, visible: true },
      { id: 'task_count', title: 'Tasks', type: 'number', width: 80, visible: true },
      { id: 'progress', title: 'Progress', type: 'percent', width: 90, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'epics',
    name: 'Epics',
    icon: '⚡',
    color: '#8b5cf6',
    endpoint: '/projects/default/epics',
    description: 'Epics & initiatives',
    responseKeys: ['items', 'epics', 'results'],
    fields: [
      { id: 'title', title: 'Title', type: 'text', width: 280, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 130, visible: true, options: EPIC_STATUS_OPTIONS },
      { id: 'priority', title: 'Priority', type: 'singleSelect', width: 110, visible: true, options: PRIORITY_OPTIONS },
      { id: 'owner_name', title: 'Owner', type: 'text', width: 150, visible: true },
      { id: 'start_date', title: 'Start', type: 'date', width: 130, visible: true },
      { id: 'end_date', title: 'End', type: 'date', width: 130, visible: true },
      { id: 'task_count', title: 'Tasks', type: 'number', width: 80, visible: true },
      { id: 'progress', title: 'Progress', type: 'percent', width: 90, visible: true },
      { id: 'parent_epic_id', title: 'Parent Epic', type: 'text', width: 120, visible: false },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'milestones',
    name: 'Milestones',
    icon: '🏁',
    color: '#0ea5e9',
    endpoint: '/tasks/advanced/projects/default/milestones',
    description: 'Project milestones',
    responseKeys: ['items', 'milestones', 'results'],
    fields: [
      { id: 'name', title: 'Name', type: 'text', width: 260, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: [
        { value: 'upcoming', label: 'Upcoming', color: '#6b7280' },
        { value: 'in_progress', label: 'In Progress', color: '#3b82f6' },
        { value: 'completed', label: 'Completed', color: '#22c55e' },
        { value: 'missed', label: 'Missed', color: '#ef4444' },
      ] },
      { id: 'due_date', title: 'Due Date', type: 'date', width: 130, visible: true },
      { id: 'completed_at', title: 'Completed', type: 'date', width: 130, visible: true },
      { id: 'task_count', title: 'Tasks', type: 'number', width: 80, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
    ],
  },

  // ==================== CONTENT & DOCS ====================
  {
    id: 'pages',
    name: 'Pages',
    icon: '📄',
    color: '#64748b',
    endpoint: '/projects/default/pages',
    description: 'Wiki & documentation',
    responseKeys: ['items', 'pages', 'results'],
    fields: [
      { id: 'title', title: 'Title', type: 'text', width: 300, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: [
        { value: 'draft', label: 'Draft', color: '#6b7280' },
        { value: 'published', label: 'Published', color: '#22c55e' },
        { value: 'archived', label: 'Archived', color: '#f59e0b' },
      ] },
      { id: 'owner_name', title: 'Owner', type: 'text', width: 150, visible: true },
      { id: 'parent_page_id', title: 'Parent', type: 'text', width: 120, visible: false },
      { id: 'is_favorite', title: 'Favorite', type: 'checkbox', width: 80, visible: true },
      { id: 'is_locked', title: 'Locked', type: 'checkbox', width: 80, visible: false },
      { id: 'view_count', title: 'Views', type: 'number', width: 80, visible: true },
      { id: 'version', title: 'Version', type: 'number', width: 70, visible: false },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
      { id: 'updated_at', title: 'Updated', type: 'date', width: 130, visible: true },
    ],
  },

  // ==================== ACADEMY ====================
  {
    id: 'discussions',
    name: 'Discussions',
    icon: '💬',
    color: '#059669',
    endpoint: '/api/academy/discussions',
    description: 'Academy forum & Q&A',
    responseKeys: ['items', 'discussions', 'results'],
    fields: [
      { id: 'title', title: 'Title', type: 'text', width: 300, visible: true, primary: true },
      { id: 'discussion_type', title: 'Type', type: 'singleSelect', width: 120, visible: true, options: DISCUSSION_TYPE_OPTIONS },
      { id: 'author_name', title: 'Author', type: 'text', width: 150, visible: true },
      { id: 'course_name', title: 'Course', type: 'text', width: 160, visible: true },
      { id: 'is_answered', title: 'Answered', type: 'checkbox', width: 90, visible: true },
      { id: 'is_pinned', title: 'Pinned', type: 'checkbox', width: 80, visible: false },
      { id: 'reply_count', title: 'Replies', type: 'number', width: 80, visible: true },
      { id: 'upvote_count', title: 'Upvotes', type: 'number', width: 80, visible: true },
      { id: 'view_count', title: 'Views', type: 'number', width: 80, visible: false },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
      { id: 'last_activity_at', title: 'Last Activity', type: 'date', width: 130, visible: true },
    ],
  },


  // ==================== GROUPS ====================
  {
    id: 'groups',
    name: 'Groups',
    icon: '👥',
    color: '#8b5cf6',
    endpoint: '/groups',
    description: 'Community groups',
    responseKeys: ['items', 'groups', 'results'],
    fields: [
      { id: 'avatar_url', title: 'Avatar', type: 'image', width: 50, visible: true },
      { id: 'name', title: 'Name', type: 'text', width: 240, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: true },
      { id: 'category', title: 'Category', type: 'singleSelect', width: 140, visible: true, options: CATEGORY_OPTIONS },
      { id: 'member_count', title: 'Members', type: 'number', width: 90, visible: true },
      { id: 'is_public', title: 'Public', type: 'checkbox', width: 80, visible: true },
      { id: 'is_member', title: 'Joined', type: 'checkbox', width: 80, visible: true },
      { id: 'channel_slug', title: 'Channel', type: 'text', width: 140, visible: false },
      { id: 'tags', title: 'Tags', type: 'text', width: 160, visible: true },
    ],
  },

  // ==================== DOCUMENTS ====================
  {
    id: 'documents',
    name: 'Documents',
    icon: '📝',
    color: '#2563eb',
    endpoint: '/api/documents?user_id=demo-user',
    description: 'Docs & knowledge base',
    responseKeys: ['documents', 'items', 'results'],
    fields: [
      { id: 'title', title: 'Title', type: 'text', width: 300, visible: true, primary: true },
      { id: 'document_type', title: 'Type', type: 'text', width: 120, visible: true },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: STATUS_OPTIONS },
      { id: 'word_count', title: 'Words', type: 'number', width: 80, visible: true },
      { id: 'reading_time_minutes', title: 'Read Time', type: 'number', width: 80, visible: true },
      { id: 'version_count', title: 'Versions', type: 'number', width: 80, visible: true },
      { id: 'comment_count', title: 'Comments', type: 'number', width: 90, visible: true },
      { id: 'view_count', title: 'Views', type: 'number', width: 80, visible: true },
      { id: 'is_pinned', title: 'Pinned', type: 'checkbox', width: 80, visible: false },
      { id: 'is_archived', title: 'Archived', type: 'checkbox', width: 80, visible: false },
      { id: 'is_locked', title: 'Locked', type: 'checkbox', width: 80, visible: false },
      { id: 'is_favorite', title: 'Favorite', type: 'checkbox', width: 80, visible: true },
      { id: 'tags', title: 'Tags', type: 'text', width: 160, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
      { id: 'updated_at', title: 'Updated', type: 'date', width: 130, visible: true },
    ],
  },

  // ==================== SOCIAL MEDIA ====================
  {
    id: 'social_posts',
    name: 'Posts',
    icon: '📱',
    color: '#e11d48',
    endpoint: '/api/social-media/posts?user_id=demo-user',
    description: 'Social media posts',
    responseKeys: ['posts', 'items', 'results'],
    fields: [
      { id: 'title', title: 'Title', type: 'text', width: 260, visible: true, primary: true },
      { id: 'content', title: 'Content', type: 'longText', width: 300, visible: true },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: [
        { value: 'draft', label: 'Draft', color: '#6b7280' },
        { value: 'scheduled', label: 'Scheduled', color: '#f59e0b' },
        { value: 'published', label: 'Published', color: '#22c55e' },
        { value: 'failed', label: 'Failed', color: '#ef4444' },
      ] },
      { id: 'platforms', title: 'Platforms', type: 'text', width: 140, visible: true },
      { id: 'approval_status', title: 'Approval', type: 'singleSelect', width: 120, visible: true, options: [
        { value: 'pending', label: 'Pending', color: '#f59e0b' },
        { value: 'approved', label: 'Approved', color: '#22c55e' },
        { value: 'rejected', label: 'Rejected', color: '#ef4444' },
      ] },
      { id: 'ai_generated', title: 'AI', type: 'checkbox', width: 60, visible: true },
      { id: 'hashtags', title: 'Hashtags', type: 'text', width: 180, visible: false },
      { id: 'link_url', title: 'Link', type: 'url', width: 200, visible: false },
      { id: 'scheduled_at', title: 'Scheduled', type: 'date', width: 130, visible: true },
      { id: 'published_at', title: 'Published', type: 'date', width: 130, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'social_accounts',
    name: 'Accounts',
    icon: '🔗',
    color: '#0891b2',
    endpoint: '/api/social-media/accounts?user_id=demo-user',
    description: 'Connected social accounts',
    responseKeys: ['accounts', 'items', 'results'],
    fields: [
      { id: 'profile_image_url', title: 'Avatar', type: 'image', width: 50, visible: true },
      { id: 'display_name', title: 'Name', type: 'text', width: 200, visible: true, primary: true },
      { id: 'platform', title: 'Platform', type: 'text', width: 120, visible: true },
      { id: 'platform_username', title: 'Username', type: 'text', width: 160, visible: true },
      { id: 'account_type', title: 'Type', type: 'text', width: 100, visible: true },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 110, visible: true, options: STATUS_OPTIONS },
      { id: 'health_status', title: 'Health', type: 'text', width: 100, visible: true },
      { id: 'health_message', title: 'Health Note', type: 'text', width: 200, visible: false },
      { id: 'created_at', title: 'Connected', type: 'date', width: 130, visible: true },
    ],
  },

  // ==================== MESSAGING ====================
  {
    id: 'conversations',
    name: 'Conversations',
    icon: '💬',
    color: '#0ea5e9',
    endpoint: '/api/messaging/conversations',
    description: 'Message threads',
    responseKeys: ['conversations', 'items', 'results'],
    fields: [
      { id: 'name', title: 'Name', type: 'text', width: 240, visible: true, primary: true },
      { id: 'type', title: 'Type', type: 'text', width: 100, visible: true },
      { id: 'participant_count', title: 'Participants', type: 'number', width: 100, visible: true },
      { id: 'unread_count', title: 'Unread', type: 'number', width: 80, visible: true },
      { id: 'last_message_at', title: 'Last Message', type: 'date', width: 150, visible: true },
    ],
  },

  // ==================== CALENDAR ====================
  {
    id: 'calendar_events',
    name: 'Events',
    icon: '📅',
    color: '#059669',
    endpoint: '/api/calendar/events?user_id=demo-user',
    description: 'Calendar events',
    responseKeys: ['events', 'items', 'results'],
    fields: [
      { id: 'title', title: 'Title', type: 'text', width: 280, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'location', title: 'Location', type: 'text', width: 180, visible: true },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 110, visible: true, options: [
        { value: 'confirmed', label: 'Confirmed', color: '#22c55e' },
        { value: 'tentative', label: 'Tentative', color: '#f59e0b' },
        { value: 'cancelled', label: 'Cancelled', color: '#ef4444' },
      ] },
      { id: 'start_at', title: 'Start', type: 'date', width: 150, visible: true },
      { id: 'end_at', title: 'End', type: 'date', width: 150, visible: true },
      { id: 'all_day', title: 'All Day', type: 'checkbox', width: 70, visible: true },
      { id: 'rrule', title: 'Recurrence', type: 'text', width: 140, visible: false },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
    ],
  },

  // ==================== ACADEMY ====================
  {
    id: 'courses',
    name: 'Courses',
    icon: '📚',
    color: '#7c3aed',
    endpoint: '/api/academy/courses',
    description: 'Learning courses',
    responseKeys: ['courses', 'items', 'results'],
    fields: [
      { id: 'image_url', title: 'Image', type: 'image', width: 60, visible: true },
      { id: 'title', title: 'Title', type: 'text', width: 280, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'category', title: 'Category', type: 'singleSelect', width: 140, visible: true, options: CATEGORY_OPTIONS },
      { id: 'level', title: 'Level', type: 'singleSelect', width: 110, visible: true, options: [
        { value: 'beginner', label: 'Beginner', color: '#22c55e' },
        { value: 'intermediate', label: 'Intermediate', color: '#f59e0b' },
        { value: 'advanced', label: 'Advanced', color: '#ef4444' },
      ] },
      { id: 'state', title: 'State', type: 'singleSelect', width: 110, visible: true, options: STATUS_OPTIONS },
      { id: 'instructor_name', title: 'Instructor', type: 'text', width: 160, visible: true },
      { id: 'duration', title: 'Duration', type: 'text', width: 100, visible: true },
      { id: 'module_count', title: 'Modules', type: 'number', width: 80, visible: true },
      { id: 'lesson_count', title: 'Lessons', type: 'number', width: 80, visible: true },
      { id: 'enrolled_count', title: 'Enrolled', type: 'number', width: 90, visible: true },
      { id: 'rating_avg', title: 'Rating', type: 'rating', width: 100, visible: true },
      { id: 'rating_count', title: 'Ratings', type: 'number', width: 80, visible: false },
      { id: 'tags', title: 'Tags', type: 'text', width: 160, visible: false },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
      { id: 'published_at', title: 'Published', type: 'date', width: 130, visible: true },
    ],
  },

  // ==================== GRANT WRITER ====================
  {
    id: 'grant_runs',
    name: 'Grant Runs',
    icon: '📋',
    color: '#b45309',
    endpoint: '/api/grantwriter/runs',
    description: 'Grant writing runs',
    responseKeys: ['runs', 'items', 'results'],
    fields: [
      { id: 'title', title: 'Title', type: 'text', width: 280, visible: true, primary: true },
      { id: 'status', title: 'Status', type: 'singleSelect', width: 120, visible: true, options: [
        { value: 'pending', label: 'Pending', color: '#f59e0b' },
        { value: 'running', label: 'Running', color: '#3b82f6' },
        { value: 'completed', label: 'Completed', color: '#22c55e' },
        { value: 'failed', label: 'Failed', color: '#ef4444' },
      ] },
      { id: 'grant_type', title: 'Grant Type', type: 'text', width: 150, visible: true },
      { id: 'funder', title: 'Funder', type: 'text', width: 180, visible: true },
      { id: 'amount', title: 'Amount', type: 'currency', width: 120, visible: true },
      { id: 'deadline', title: 'Deadline', type: 'date', width: 130, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
    ],
  },

  // ==================== STORAGE ====================
  {
    id: 'storage_objects',
    name: 'Files',
    icon: '📁',
    color: '#78716c',
    endpoint: '/api/storage/objects',
    description: 'Uploaded files & media',
    responseKeys: ['items', 'objects', 'results'],
    fields: [
      { id: 'name', title: 'Name', type: 'text', width: 280, visible: true, primary: true },
      { id: 'bucket', title: 'Bucket', type: 'text', width: 120, visible: true },
      { id: 'mime_type', title: 'Type', type: 'text', width: 140, visible: true },
      { id: 'size_bytes', title: 'Size (bytes)', type: 'number', width: 110, visible: true },
      { id: 'owner_name', title: 'Owner', type: 'text', width: 150, visible: true },
      { id: 'module', title: 'Module', type: 'text', width: 120, visible: true },
      { id: 'is_deleted', title: 'Deleted', type: 'checkbox', width: 80, visible: false },
      { id: 'path', title: 'Path', type: 'text', width: 300, visible: false },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
      { id: 'updated_at', title: 'Updated', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'storage_buckets',
    name: 'Buckets',
    icon: '🗄',
    color: '#a8a29e',
    endpoint: '/api/storage/buckets',
    description: 'Storage buckets',
    responseKeys: ['items', 'buckets', 'results'],
    fields: [
      { id: 'name', title: 'Name', type: 'text', width: 200, visible: true, primary: true },
      { id: 'object_count', title: 'Objects', type: 'number', width: 90, visible: true },
      { id: 'total_size_bytes', title: 'Total Size', type: 'number', width: 110, visible: true },
      { id: 'is_public', title: 'Public', type: 'checkbox', width: 80, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
    ],
  },

  // ==================== SYSTEM ====================
  {
    id: 'templates',
    name: 'Templates',
    icon: '📑',
    color: '#ca8a04',
    endpoint: '/tasks/advanced/templates',
    description: 'Task templates',
    responseKeys: ['items', 'templates', 'results'],
    fields: [
      { id: 'name', title: 'Name', type: 'text', width: 260, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'category', title: 'Category', type: 'text', width: 140, visible: true },
      { id: 'is_global', title: 'Global', type: 'checkbox', width: 80, visible: true },
      { id: 'task_count', title: 'Tasks', type: 'number', width: 80, visible: true },
      { id: 'use_count', title: 'Uses', type: 'number', width: 80, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: true },
    ],
  },
  {
    id: 'automation_rules',
    name: 'Automations',
    icon: '⚙️',
    color: '#ea580c',
    endpoint: '/tasks/advanced/projects/default/automation-rules',
    description: 'Automation rules',
    responseKeys: ['items', 'rules', 'results'],
    fields: [
      { id: 'name', title: 'Name', type: 'text', width: 260, visible: true, primary: true },
      { id: 'description', title: 'Description', type: 'longText', width: 300, visible: false },
      { id: 'trigger_type', title: 'Trigger', type: 'text', width: 140, visible: true },
      { id: 'action_type', title: 'Action', type: 'text', width: 140, visible: true },
      { id: 'is_enabled', title: 'Enabled', type: 'checkbox', width: 80, visible: true },
      { id: 'run_count', title: 'Runs', type: 'number', width: 80, visible: true },
      { id: 'last_run_at', title: 'Last Run', type: 'date', width: 130, visible: true },
      { id: 'created_at', title: 'Created', type: 'date', width: 130, visible: false },
    ],
  },
  {
    id: 'audit_logs',
    name: 'Audit Log',
    icon: '📊',
    color: '#475569',
    endpoint: '/api/storage/audit-logs',
    description: 'System audit trail',
    responseKeys: ['items', 'logs', 'results'],
    fields: [
      { id: 'action', title: 'Action', type: 'text', width: 160, visible: true, primary: true },
      { id: 'actor_name', title: 'Actor', type: 'text', width: 150, visible: true },
      { id: 'resource_type', title: 'Resource', type: 'text', width: 120, visible: true },
      { id: 'resource_name', title: 'Resource Name', type: 'text', width: 200, visible: true },
      { id: 'bucket', title: 'Bucket', type: 'text', width: 120, visible: true },
      { id: 'details', title: 'Details', type: 'longText', width: 300, visible: false },
      { id: 'ip_address', title: 'IP', type: 'text', width: 120, visible: false },
      { id: 'created_at', title: 'Timestamp', type: 'date', width: 160, visible: true },
    ],
  },
];

// Helper to pick tables by id
function pick(...ids: string[]): TableDef[] {
  return ids.map(id => ALL_TABLES.find(t => t.id === id)!).filter(Boolean);
}

// ---------------------------------------------------------------------------
// Database Definitions — maps to app sections from sidebar
// ---------------------------------------------------------------------------

export const DATABASES: DatabaseDef[] = [
  {
    id: 'profiles',
    name: 'Street Profile',
    icon: '👤',
    color: '#ec4899',
    description: 'User & creative profiles',
    tables: pick('profiles'),
  },
  {
    id: 'news',
    name: 'News',
    icon: '📰',
    color: '#a855f7',
    description: 'Articles & coverage',
    tables: pick('news'),
  },
  {
    id: 'groups',
    name: 'Groups',
    icon: '👥',
    color: '#8b5cf6',
    description: 'Community groups & channels',
    tables: pick('groups'),
  },
  {
    id: 'messages',
    name: 'Messages',
    icon: '💬',
    color: '#0ea5e9',
    description: 'Conversations & messaging',
    tables: pick('conversations'),
  },
  {
    id: 'directory',
    name: 'Directory',
    icon: '📍',
    color: '#06b6d4',
    description: 'Community services & organizations',
    tables: pick('directory'),
  },
  {
    id: 'jobs',
    name: 'Job Board',
    icon: '💼',
    color: '#3b82f6',
    description: 'Job postings & opportunities',
    tables: pick('jobs'),
  },
  {
    id: 'academy',
    name: 'Academy',
    icon: '🎓',
    color: '#7c3aed',
    description: 'Learning & community education',
    tables: pick('courses', 'discussions'),
  },
  {
    id: 'calendar',
    name: 'Calendar',
    icon: '📅',
    color: '#059669',
    description: 'Events & scheduling',
    tables: pick('calendar_events'),
  },
  {
    id: 'social-media',
    name: 'Social Media',
    icon: '📱',
    color: '#e11d48',
    description: 'Social media management',
    tables: pick('social_posts', 'social_accounts'),
  },
  {
    id: 'project-management',
    name: 'Tasks',
    icon: '✅',
    color: '#22c55e',
    description: 'Project management & work tracking',
    tables: pick('tasks', 'projects', 'cycles', 'modules', 'epics', 'milestones'),
  },
  {
    id: 'documents',
    name: 'Documents',
    icon: '📝',
    color: '#2563eb',
    description: 'Docs, wikis & knowledge base',
    tables: pick('documents', 'pages'),
  },
  {
    id: 'storage',
    name: 'Storage',
    icon: '📁',
    color: '#78716c',
    description: 'Files, media & uploads',
    tables: pick('storage_objects', 'storage_buckets'),
  },
  {
    id: 'grantwriter',
    name: 'Grant Writer',
    icon: '✍️',
    color: '#b45309',
    description: 'Grant applications & writing',
    tables: pick('grant_runs'),
  },
  {
    id: 'system',
    name: 'System',
    icon: '⚙️',
    color: '#6b7280',
    description: 'Templates, automations & audit logs',
    tables: pick('templates', 'automation_rules', 'audit_logs'),
  },
];

// Flat list for backwards compatibility
export const TABLES: TableDef[] = ALL_TABLES;

// ---------------------------------------------------------------------------
// Default Views
// ---------------------------------------------------------------------------

export const DEFAULT_VIEWS: ViewDef[] = [
  { id: 'grid', type: 'grid', name: 'Grid', icon: '⊞' },
  { id: 'gallery', type: 'gallery', name: 'Gallery', icon: '▦' },
  { id: 'kanban', type: 'kanban', name: 'Kanban', icon: '▥' },
  { id: 'calendar', type: 'calendar', name: 'Calendar', icon: '📅' },
  { id: 'form', type: 'form', name: 'Form', icon: '☐' },
];
